//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weather
    {
        public int Id { get; set; }
        public int PositionId { get; set; }
        public double Temperature { get; set; }
        public string City { get; set; }
        public System.DateTime ValidTime { get; set; }
        public System.DateTime NextUpdate { get; set; }
        public string SymbolUrl { get; set; }
    
        public virtual Position Position { get; set; }
    }
}
